### ISSUE TITLE
Set env command

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/live-platform#481]

**Comment by BFergerson** [comment]
Will need to update `spp-plugin.yml` to do this. Something like:
```yaml
override: true
service_host: "https://tenant1.sourceplus.plus"
authorization_code: "spp-oss"
service_name: "spp-platform-ci"

environments:
  - name: "demo"
    service_host: "https://tenant1.sourceplus.plus"
  - name: "local"
    service_host: "http://localhost:12800"
```
